# Generated by Django 4.2.15 on 2024-08-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_appointment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
