# Generated by Django 4.2.15 on 2024-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_appointment_reminder_sent_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consecutive_missed_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
