# Generated by Django 4.2.15 on 2024-09-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_consecutive_missed_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='missed_counted',
            field=models.BooleanField(default=False),
        ),
    ]
