# Generated by Django 4.2.15 on 2024-09-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_appointment_missed_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
