# Generated by Django 4.2.15 on 2024-09-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_user_has_seen_privacy_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_seen_privacy_policy',
            new_name='has_agreed_privacy_policy',
        ),
    ]
