# Generated by Django 4.2.15 on 2024-09-12 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician_care', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('allergic', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('blood_disease', models.BooleanField(default=False)),
                ('bleeder', models.BooleanField(default=False)),
                ('excessive_bleeding', models.BooleanField(default=False)),
                ('recent_infection', models.BooleanField(default=False)),
                ('anesthetic_reactions', models.BooleanField(default=False)),
                ('previous_dental_surgery', models.BooleanField(default=False)),
                ('health_impression', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
