# Generated by Django 4.2.15 on 2024-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_medicalquestionnaire_allergic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='allergic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='anesthetic_reactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='bleeder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='blood_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='excessive_bleeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='physician_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='previous_dental_surgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalquestionnaire',
            name='recent_infection',
            field=models.BooleanField(default=False),
        ),
    ]
