# Generated by Django 4.2.15 on 2024-10-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_user_has_completed_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_completed_questionnaire',
        ),
    ]
