# Generated by Django 4.2.15 on 2024-10-30 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_user_has_completed_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
