# Generated by Django 4.2.15 on 2024-11-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_user_managers_user_identifier_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
