# Generated by Django 4.2.15 on 2024-12-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='other_concern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
