# Generated by Django 4.2.15 on 2024-12-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_rename_other_concern_appointment_custom_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='custom_concern',
        ),
    ]
