# Generated by Django 4.2.15 on 2024-12-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='custom_concern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.service'),
        ),
    ]
